//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLINIC()
        {
            this.DOCTORS = new HashSet<DOCTOR>();
        }
    
        public int ClinicID { get; set; }
        public string CLINICGoogleUID { get; set; }
        public string ClinicName { get; set; }
        public string CLINICADDRESS { get; set; }
        public string ClinicEmail { get; set; }
        public string ClinicTelePhone { get; set; }
        public string CLINICWorkingHours { get; set; }
        public string ClinicWebsite { get; set; }
        public Nullable<int> USERID { get; set; }
        public string USERNAME { get; set; }
        public System.DateTime USERSearchDATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR> DOCTORS { get; set; }
    }
}
