//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTORSUSERRATING
    {
        public int USERRATINGID { get; set; }
        public Nullable<int> DOCTORID { get; set; }
        public string DOCTORNAME { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public string ClinicName { get; set; }
        public Nullable<int> USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERCOMMENTS { get; set; }
        public System.DateTime USERSearchDATETIME { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
    }
}
