USE [master]
GO

/****** Object:  Database [DBPATIENTNOWAIT]    Script Date: 28-02-2017 14:33:24 ******/
CREATE DATABASE [DBPATIENTNOWAIT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBPATIENTNOWAIT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.PROACTIVE\MSSQL\DATA\DBPATIENTNOWAIT.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBPATIENTNOWAIT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.PROACTIVE\MSSQL\DATA\DBPATIENTNOWAIT_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBPATIENTNOWAIT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET RECOVERY FULL 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET  MULTI_USER 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBPATIENTNOWAIT] SET  READ_WRITE 
GO


