USE [DBPATIENTNOWAIT]
GO

/****** Object:  Table [dbo].[DOCTORS]    Script Date: 01-03-2017 11:28:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DOCTORS](
	[DOCTORID] [int] NOT NULL,
	[DOCTORNAME] [varchar](8000) NULL,
	[DOCTORADDRESS] [varchar](8000) NULL,
	[DOCTOREmail] [varchar](8000) NULL,
	[DOCTORTelePhone] [varchar](8000) NULL,
	[DOCTORWorkingHours] [varchar](8000) NULL,
	[ClinicID] [int] NULL,
	[CLINICGoogleUID] [varchar](8000) NULL,
	[ClinicName] [varchar](8000) NULL,
	[USERID] [int] NULL,
	[USERNAME] [varchar](8000) NULL,
	[USERSearchDATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK__DOCTORS__7ECABDCC32CF8520] PRIMARY KEY CLUSTERED 
(
	[DOCTORID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DOCTORS] ADD  CONSTRAINT [DF__DOCTORS__USERSea__1A14E395]  DEFAULT (getdate()) FOR [USERSearchDATETIME]
GO

ALTER TABLE [dbo].[DOCTORS]  WITH CHECK ADD  CONSTRAINT [FK__DOCTORS__ClinicI__25869641] FOREIGN KEY([ClinicID])
REFERENCES [dbo].[CLINICS] ([ClinicID])
GO

ALTER TABLE [dbo].[DOCTORS] CHECK CONSTRAINT [FK__DOCTORS__ClinicI__25869641]
GO


