USE [DBPATIENTNOWAIT]
GO

/****** Object:  Table [dbo].[DOCTORSUSERRATINGS]    Script Date: 04-03-2017 10:15:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DOCTORSUSERRATINGS](
	[USERRATINGID] [int] NOT NULL,
	[DOCTORID] [int] NULL,
	[DOCTORNAME] [varchar](8000) NULL,
	[ClinicID] [int] NULL,
	[ClinicName] [varchar](8000) NULL,
	[USERID] [int] NULL,
	[USERNAME] [varchar](8000) NULL,
	[USERCOMMENTS] [varchar](8000) NULL,
	[USERSearchDATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK__DOCTORSU__62FF97EA35493AF5] PRIMARY KEY CLUSTERED 
(
	[USERRATINGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DOCTORSUSERRATINGS] ADD  CONSTRAINT [DF__DOCTORSUS__USERS__36B12243]  DEFAULT (getdate()) FOR [USERSearchDATETIME]
GO

ALTER TABLE [dbo].[DOCTORSUSERRATINGS]  WITH CHECK ADD  CONSTRAINT [FK__DOCTORSUS__DOCTO__37A5467C] FOREIGN KEY([DOCTORID])
REFERENCES [dbo].[DOCTORS] ([DOCTORID])
GO

ALTER TABLE [dbo].[DOCTORSUSERRATINGS] CHECK CONSTRAINT [FK__DOCTORSUS__DOCTO__37A5467C]
GO


